name = "MinIO Hugo Docs Theme"
license = "Apache-2."
description = "Hugo theme for MinIO Documentations"
homepage = "https://min.io/"
demosite = "https://min.io/"
tags = ["minio", "minio-documentation", "minio kes", "kes"]
min_version = "0.93.0"

[author]
name = "Team MinIO"
homepage = "https://min.io/"

# Configs for the project (../../config.toml)
[params]
footerText = 'This work is licensed under a Creative Commons Attribution 4.0 International License. 2020-Present, MinIO, Inc.'
homeLink = '/'
enableGitInfo = true

[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
noclasses = false

[menu]
# Platform
[[menu.platform]]
name = 'Kubernetes'
url = 'https://min.io/docs/minio/kubernetes/upstream/index.html'
pre = 'k8s'
weight = 1
[menu.platform.params]
activeFill = '#1a6fd3'
[[menu.platform]]
name = 'Docker'
url = 'https://min.io/docs/minio/container/index.html'
pre = 'docker'
weight = 2
[menu.platform.params]
activeFill = '#2497ed'
[[menu.platform]]
name = 'Linux'
url = 'https://min.io/docs/minio/linux/index.html'
pre = 'linux'
weight = 3
[[menu.platform]]
name = 'macOS'
url = 'https://min.io/docs/minio/macos/index.html'
pre = 'macos'
weight = 4
[menu.platform.params]
activeFill = '#959595'
[[menu.platform]]
name = 'windows'
url = 'https://min.io/docs/minio/windows/index.html'
pre = 'windows'
weight = 5
[menu.platform.params]
activeFill = '#0076d2'
[[menu.docs]]
name = "KES Documentation"
weight = 1
[menu.docs.params]
current = true
[[menu.docs]]
name = "MinIO Documentation"
url = "https://min.io/docs/minio/kubernetes/upstream/index.html"
weight = 2
[[menu.docs]]
name = "DirectPV Documentation"
url = "https://min.io/docs/directpv"
weight = 3
